<P><B>Enige opmaak-tips:</B>
<TABLE CELLPADDING=5 BORDER=5>
<TR><TD>alinea.<BR>&nbsp;Overgang</TD><TD>alinea.<BR>&nbsp;<BR>Overgang</TD></TR>
<TR><TD>regel<BR>overgang</TD><TD>regel \\<BR>overgang</TD></TR>
<TR><TD><EM>schuin</EM></TD><TD>\emph{schuin}</TD></TR>
<TR><TD><B>vet</B></TD><TD>\textbf{vet}</TD></TR>
<TR><TD>bijv. drie</TD><TD>bijv.\ drie</TD></TR>
<TR><TD>altijd&nbsp;samen</TD><TD>altijd~samen</TD></TR>
<TR><TD>\</TD><TD>\\</TD></TR>
<TR><TD>.&nbsp;.&nbsp;.&nbsp;</TD><TD>\ldots</TD></TR>
<TR><TD>ként rènt cënt qïnt</TD><TD>k\'ent r\`ent c\"ent q\" \i nt</TD></TR>
<TR>
	<TD><UL><LI>één<LI>twee</UL></TD>
	<TD>\begin{itemize}<BR>\item \'e\'en<BR>\item twee<BR>\end{itemize}</TD>
</TR>
<TR>
	<TD><OL><LI>één<LI>twee</OL></TD>
	<TD>\begin{enumerate}<BR>\item \'e\'en<BR>\item twee<BR>\end{enumerate}</TD>
</TR>
</TABLE>
</P>
